config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  Spree::Core::Engine.add_routes do
    # Routes to different categories
    get '/special-deals', to: 'products#special_deals', as: :special_deals
    patch '/order/remove_item', to: 'orders#remove_item', as: :remove_item
    scope :categories do
      get '/:category', to: 'home#show', as: :category
      get '/:category/:package_name', to: 'packages#show', as: :package

      post '/:category/:id', to: 'packages#add', as: :add_package
      post '/:category/customized/:package_name', to: 'packages#add_customized', as: :add_customized_package
    end
  end
end

app/controllers/spree/home_controller.rb
class Spree::HomeController < Spree::StoreController
  before_action :set_user, :set_order

  def index
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

  def show
    if params[:category] == "laptop"
      set_packages(0)
    elsif params[:category] == "desktop"
      set_packages(3)
    elsif params[:category] == "workstation"
      set_packages(6)
    end

    @basic_stock = package_has_stock(@basic)
    @standard_stock = package_has_stock(@standard)
    @premium_stock = package_has_stock(@premium)
  end

  private

  # Define the packages for each landing page choices (laptop, desktop, workstation)
  def set_packages(n)
    @basic = Spree::Taxonomy.all[n]
    @standard = Spree::Taxonomy.all[n+1]
    @premium = Spree::Taxonomy.all[n+2]
  end

  def package_has_stock(package)
    set_products(package)

    @products.each do |p|
      if p.stock_items.first.count_on_hand <= 0
        return false
      end
    end

    return true
  end

  def set_products(package)
    # Define the taxon that include all the package items
    @taxon = package.taxons.first
    return unless @taxon

    # Find all products in the package
    @searcher = build_searcher(params.merge(taxon: @taxon.id, include_images: true))
    @products = @searcher.retrieve_products.where("meta_keywords like?", "%#{package.name.split.map(&:downcase).join('_')}_default%")
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end

end

app/views/spree/home/partials/_basic.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-1">
    <div class="package-overview-details text-left">
      <div class="row">
        <i class="fa fa-phone fa-lg" aria-hidden="true"></i>
        <h6>More Info:</h6>
        <p>Call 06 06 06 06 06</p>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <div class="package-overview-details text-left">
      <i class="fa fa-shopping-bag fa-lg" aria-hidden="true"></i>
      <h6>Delivery:</h6>
      <p>In Stock</p>
      <p>Free Shipping</p>
    </div>
  </div>
  <div class="col-md-2">
    <div class="package-overview-details text-left">
      <div><i class="fa fa-euro fa-lg" aria-hidden="true"></i></div>
      <h6><b class="package-price-details">2,058</b></h6>
    </div>
  </div>
  <div class="col-md-5">
    <div class="package-customize-btn-grp text-right row">
      <%= link_to package_path(package_name: @basic.name.downcase), class: "btn btn-primary package-customize-btn" do %>
        <i class="fa fa-edit"></i>&nbsp;&nbsp;Customize
      <% end %>
    </div>
    <%= simple_form_for :package, html: { class: "text-right row clearfix" }, url: add_package_path(@basic, category: params[:category], package_name: @basic.name.downcase) do |f| %>
      <h6 class="text-center col-md-4">Quick add</h6>
      <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3 no-padding" }, label: false %>
      <div class="col-md-5 text-right no-padding">
        <%= button_tag(type: 'submit', class: "btn btn-success package-customize-btn") do %>
          <i class="fa fa-cart-arrow-down"></i>&nbsp;&nbsp;Add to cart
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/home/partials/_basic_desktop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @basic_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6><%= Spree.t(:in_stock) %></h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red"><%= Spree.t(:out_of_stock) %></h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6><%= Spree.t(:livraison_gratuite) %></h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,058 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@basic, category: params[:category], package_name: @basic.name.downcase) do |f| %>
    <h6 class="text-center col-md-4"><%= Spree.t(:ajout_rapide) %></h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %><%= Spree.t(:add_to_cart) %>
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @basic.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_basic_laptop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @basic_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6><%= Spree.t(:in_stock) %></h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red"><%= Spree.t(:out_of_stock) %></h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6><%= Spree.t(:livraison_gratuite) %></h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,058 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@basic, category: params[:category], package_name: @basic.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        <%= Spree.t(:add_to_cart) %>
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @basic.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_basic_workstation.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @basic_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6><%= Spree.t(:in_stock) %></h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red"><%= Spree.t(:out_of_stock) %></h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6><%= Spree.t(:livraison_gratuite) %></h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,058 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@basic, category: params[:category], package_name: @basic.name.downcase) do |f| %>
    <h6 class="text-center col-md-4"><%= Spree.t(:ajout_rapide) %></h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        <%= Spree.t(:add_to_cart) %>
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @basic.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_desktop.html.erb
<div class="container-fluid">
  <h3 class="text-center"><%= Spree.t(:resume_pack2_title) %></h3>

  <section class="package-selection homepage-section row">
    <div class="col-md-8 col-md-offset-2">
      <ul class="nav nav-pills nav-justified">
        <li class="active package-overview-container container-desktop">
          <a data-toggle="pill" href="#basic-desktop-package" class="package-overview-select clearfix">
            <h4><%= @basic.name %></h4>
            <div class="text-center package-icon-container"><%= image_tag "desktop_gear1.png", alt: "Basic Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
            </ul>
            <b class="package-price">2,058 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
        <hr class="hidden-md hidden-lg">
        <li class="package-overview-container container-desktop">
          <a data-toggle="pill" href="#standard-desktop-package" class="package-overview-select clearfix">
            <h4><%= @standard.name %></h4>
            <div class="text-center package-icon-container"><%= image_tag "desktop_gear2.png", alt: "Standard Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer or Apple Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
              <li>Microsoft Office</li>
            </ul>
            <b class="package-price">2,137 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
        <hr class="hidden-md hidden-lg">
        <li class="package-overview-container container-desktop">
          <a data-toggle="pill" href="#premium-desktop-package" class="package-overview-select clearfix">
            <h4><%= @premium.name %></h4>
            <div class="text-center package-icon-container"><%= image_tag "desktop_gear3.png", alt: "Premium Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer or Apple Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
              <li>Microsoft Office</li>
              <li>External Monitor</li>
            </ul>
            <b class="package-price">2,436 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
      </ul>
    </div>
  </section>

  <section class="package-details row">
    <div class="tab-content col-md-8 col-md-offset-2">
      <div id="basic-desktop-package" class="tab-pane fade in active">
        <div><%= render "spree/home/partials/basic_desktop" %></div>
      </div>
      <div id="standard-desktop-package" class="tab-pane fade">
        <div><%= render "spree/home/partials/standard_desktop" %></div>
      </div>
      <div id="premium-desktop-package" class="tab-pane fade">
        <div><%= render "spree/home/partials/premium_desktop" %></div>
      </div>
    </div>
  </section>
</div>

app/views/spree/home/partials/_laptop.html.erb
<div class="container-fluid">
  <h3 class="text-center"><%= Spree.t(:resume_pack1_title) %></h3>

  <section class="package-selection homepage-section row">
     <div class="col-md-8 col-md-offset-2">
      <ul class="nav nav-pills nav-justified">
        <li class="active package-overview-container container-laptop">
          <a data-toggle="pill" href="#basic-laptop-package" class="package-overview-select clearfix">
            <h4><%= Spree.t(:resume_pack1_bussiness) %></h4>
            <div class="text-center package-icon-container"><%= image_tag "laptop_gear1.png", alt: "Basic Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
            </ul>
            <b class="package-price">2,058 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
        <hr class="hidden-md hidden-lg">
        <li class="package-overview-container container-laptop">
          <a data-toggle="pill" href="#standard-laptop-package" class="package-overview-select clearfix">
            <h4><%= Spree.t(:resume_pack1_polyvalent) %></h4>
            <div class="text-center package-icon-container"><%= image_tag "laptop_gear2.png", alt: "Standard Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer or Apple Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
              <li>Microsoft Office</li>
            </ul>
            <b class="package-price">2,137 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
        <hr class="hidden-md hidden-lg">
        <li class="package-overview-container container-laptop">
          <a data-toggle="pill" href="#premium-laptop-package" class="package-overview-select clearfix">
            <h4><%= Spree.t(:resume_pack1_performance) %></h4>
            <div class="text-center package-icon-container"><%= image_tag "laptop_gear3.png", alt: "Premium Pakage image", class: "package-icon" %></div>
            <ul class="package-overview-details text-left">
              <li>Dell Computer or Apple Computer</li>
              <li>Keyboard</li>
              <li>HP Mouse</li>
              <li>Microsoft Office</li>
              <li>External Monitor</li>
            </ul>
            <b class="package-price">2,436 €</b>
          </a>
          <div class="row lead text-center">
            <div class="starrr"></div>
            <span class="star-count">0</span>
            star(s)
          </div>
        </li>
      </ul>
    </div>
  </section>

  <section class="package-details row">
    <div class="tab-content col-md-8 col-md-offset-2">
      <div id="basic-laptop-package" class="tab-pane fade in active">
        <div><%= render "spree/home/partials/basic_laptop" %></div>
      </div>
      <div id="standard-laptop-package" class="tab-pane fade">
        <div><%= render "spree/home/partials/standard_laptop" %></div>
      </div>
      <div id="premium-laptop-package" class="tab-pane fade">
        <div><%= render "spree/home/partials/premium_laptop" %></div>
      </div>
    </div>
  </section>
</div>

app/views/spree/home/partials/_premium_desktop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @premium_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,436 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@premium, category: params[:category], package_name: @premium.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @premium.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_premium_laptop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @premium_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,436 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@premium, category: params[:category], package_name: @premium.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @premium.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_premium_workstation.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @premium_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,436 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@premium, category: params[:category], package_name: @premium.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @premium.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_standard_desktop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @standard_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,137 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@standard, category: params[:category], package_name: @standard.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @standard.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_standard_laptop.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @standard_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,137 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@standard, category: params[:category], package_name: @standard.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @standard.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/home/partials/_standard_workstation.html.erb
<div class="row package-footer">
  <div class="col-md-3 col-md-offset-1 hidden-xs hidden-sm">
    <div class="package-overview-details shipping-details">
      <ul class="list-inline">
        <% if @standard_stock %>
          <li class="text-center"><i class="fa fa-check" aria-hidden="true"></i></li>
          <li><h6>in stock</h6></li>
        <% else %>
          <li class="text-center text-red"><i class="fa fa-close" aria-hidden="true"></i></li>
          <li><h6 class="text-red">out of stock</h6></li>
        <% end %>
      </ul>
      <ul class="list-inline">
        <li><i class="fa fa-truck" aria-hidden="true"></i></li>
        <li><h6>free shipping</h6></li>
      </ul>
    </div>
  </div>
  <div class="col-md-2 hidden-xs hidden-sm text-center">
    <div class="package-overview-details">
      <b class="package-price-details">2,137 €</b>
    </div>
  </div>
  <div class="col-md-5">
    <%= simple_form_for :package, html: { class: "text-center row add-package" }, url: add_package_path(@standard, category: params[:category], package_name: @standard.name.downcase) do |f| %>
    <h6 class="text-center col-md-4">Quick add</h6>
    <%= f.input :quantity, as: :integer, input_html: { placeholder: "Quantity", class: "package-quantity-input", value: 1 }, wrapper_html: { class: "col-md-3" }, label: false %>
    <div class="col-md-5 text-center">
      <%= button_tag(type: 'submit', class: "btn btn-primary package-customize-btn add-cart") do %>
        Add to cart
      <% end %>
    </div>
  <% end %>
    <div class="package-customize-btn-grp text-center row">
      <div class="col-md-5 col-md-offset-7">
        <%= link_to package_path(package_name: @standard.name.downcase), class: "btn btn-danger package-customize-btn" do %>
          <%= Spree.t(:customize) %>
        <% end %>
      </div>
    </div>
  </div>
</div>